id: {uid}

product:
  name: waterdemand_monthly

format: GeoTIFF

creation_dt: {creation_date}
crs: EPSG:4326

geometry:
  type: Polygon
  coordinates: {polygon}

grids:
  default:
    shape: {shape}
    transform: {transform}

extent:
  lat:
    begin: {lat_min}
    end: {lat_max}
  lon:
    begin: {lon_min}
    end: {lon_max}

grid_spatial:
  projection:
    geo_ref_points:
      ll: {{x: {lon_min}, y: {lat_min}}}
      lr: {{x: {lon_max}, y: {lat_min}}}
      ul: {{x: {lon_min}, y:  {lat_max}}}
      ur: {{x: {lon_max}, y: {lat_max}}}
    spatial_reference: EPSG:4326

       
properties:
  datetime: {datetime}
  odc:file_format: GeoTIFF
  proj:epsg: 4326

measurements:
  WD:
    path: {WD}

